### ISSUE TITLE
Caso de uso de modificar usuario

### ISSUE THREAD

**Issue by Irillium** [Irillium/ed-DigitalLibrary#5]
> > > ## Descripción
> > > El cliente nos pide poder modificar al un usuario.
> > > ## Implementación
> > > 
> > > * Crear un caso de uso para modificar al usuario. (Dominio)
> > > * Implementar en el Repositoy y el DataRepositori los métodos de modificar el usuario. (Data)
> > > * Crear una opción en el menú para seleccionar la opción de modificar al usuario de forma funcional. (Presentation)
> > > 
> > > ## Definición de Hecho (DoD)
> > > 
> > > * [x]    Se muestra en el menú principal la opción de modificar a un usuario.
> > > * [x]    Se le pide al usuario que introduzca los datos necesarios para identificar el usuario y modificarlo.
> > > * [x]   Se modifica el usuario del fichero.

**Comment by karlabiggio** [comment]
Has hecho todo lo que tenias que hacer bien
